name: Build and Realease android apk

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          # Создаем папку, если она вдруг не попала в git
          mkdir -p frontend/assets/.env
          
          # Записываем секрет из настроек GitHub в реальный файл
          echo "${{ secrets.ENV_FILE_FLATTER }}" > frontend/assets/.env/.env

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: '3.19.0'

      - name: Install dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Run build_runner (Generate code)
        working-directory: ./frontend
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build apk
        working-directory: ./frontend
        run: |
          CLEAN_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          
          flutter build apk --release \
            --split-per-abi \
            --target-platform android-arm,android-arm64 \
            --tree-shake-icons \
            --no-pub \
            --build-name=$CLEAN_VERSION \
            --build-number=${{ github.run_number }}

      - name: Rename APK files
        working-directory: ./frontend
        run: |
          cd build/app/outputs/flutter-apk/
          
          APP_NAME="Cookify"
               
          # тут лежит версия
          VERSION="${{ github.event.release.tag_name }}" 
          
          # Переименовываем каждый файл
          mv app-armeabi-v7a-release.apk $APP_NAME-$VERSION-android-old.apk
          mv app-arm64-v8a-release.apk $APP_NAME-$VERSION-android-new.apk

      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            frontend/build/app/outputs/flutter-apk/*-android-old.apk
            frontend/build/app/outputs/flutter-apk/*-android-new.apk
